### ISSUE TITLE
DKIM not signing

### ISSUE THREAD

**Issue by leenooks** [vstakhov/rspamd#1582] opened 2017-04-07 14:48 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.4

### Operation system, CPU, memory and environment:
N/A
### Description (Please provide a descriptive summary of the issue):
It seems I cannot get RSPAM to sign messages unless I have `whitelist = ""`; in the spamd {} configuration of rmilter.conf even though I have `out_networks` set with my IP addresses in the global config.

I've even got "sign_networks" in the dkim {} section, but still outgoing messages are not signed.

Am I doing something wrong?

**Comment by vstakhov** [comment] 2017-04-07 15:08
You mix Rspamd and Rmilter here. It is completely not clear what are you trying to do and why.

**Comment by fatalbanana** [comment] 2017-04-07 15:11
The issue here I expect is that rmilter specifies the localhost in the whitelist by default, so messages from it are not sent to rspamd (for DKIM signing etc).

**Comment by leenooks** [comment] 2017-04-08 13:50
Hi, sorry, yes I spent a lot of time figuring out how to get DKIM working that I did leave out some details.

So, I'm using sendmail - a mail host that receives all email from the internet and sends it onto an internal mail server, and the same sendmail host receives outgoing mail to forward to a SMART_HOST destined for the internet.

So, for incoming mail, I want SPAM functions enabled (greylisting, virus checks, etc) to reduce the rubbish that comes in.

For outgoing mail, (outgoing means those from internal hosts destined to the internet), I don't want SPAM checks done (it's good mail ;) - but I do want to DKIM sign it, so that receivers mail servers hopefully won't classify it as spam. 

So in rmilter.conf.local, I had to have `whitelist = ` in the `spam {}` group for DKIM signing to be performed (but that also means the mail is being SPAM checked).

Here is the parts of my config:

```
strict_auth = true;
our_networks = 127.0.0.1/32, 10.0.0.0/8, 172.17.0.0/16;

spamd {
        extended_spam_headers = yes;
        servers = localhost:11333;
#       whitelist = 127.0.0.1/32, 10.0.0.0/8, 172.17.0.0/16;
        whitelist = '';
};

dkim {
        enable = true;
        sign_networks = 127.0.0.1/32, 10.0.0.0/8, 172.17.0.0/16;
}; 
```

If i change my whitelist back to exclude the internal hosts from SPAM checking, then DKIM signing doesn't occur?

**Comment by dehnli** [comment] 2017-04-08 19:55
@leenooks in my case DKIM signing works successfully with such `rmilter.conf`:

```
strict_auth = yes;

spamd {
        whitelist = 127.0.0.1/32, 10.0.0.0/8, 172.17.0.0/16;
}

dkim {
        enable = yes;
        domain {
                key = /path/to/dkim/key;
                domain = "example.com";
                selector = "mail";
        };
};
``` 

```
# cat /var/log/maillog
...
Apr  8 22:33:16 rspamd null[45002]: <19f00a72e3>; mlfi_eom: d=example.com, s=mail, added DKIM signature
...
```

But it's performed with _rmilter_ not Rspamd. And as @fatalbanana said it's not clear enough which settings should be for Rspamd DKIM signing. For example, should `enable` and `rspamd_sign` be `true` at the same time in `rmilter.conf`

**Comment by fatalbanana** [comment] 2017-04-08 20:13
@dehnli setting `debug_modules = ["dkim_signing"]` in `local.d/logging.inc` should offer insight into why DKIM signing module may not sign messages (you may need to adjust the default policy to suit your environment).

**Comment by dehnli** [comment] 2017-04-09 09:54
@fatalbanana @leenooks `debug_modules = ["dkim_signing"];` gave a hint _dkim_signing; dkim_signing.lua:106: domain mismatch not allowed: sub.domain.tld != domain.tld_ and I got to work Rspamd DKIM signing (`DKIM_SIGNED(0.00)[]`)

**Note:** `spamd { whitelist = ..}` is commented

`rmilter.conf:`
```
strict_auth = yes;

spamd {
#        whitelist = 127.0.0.1/32, 10.0.0.0/8, 172.17.0.0/16;
}

dkim {
        enable = no;
        rspamd_sign = yes;
};
```
`local.d/dkim_signing.conf`
```
# rspamadm configdump dkim_signing
*** Section dkim_signing ***
allow_envfrom_empty = true;
allow_hdrfrom_mismatch = true;
allow_hdrfrom_multiple = false;
allow_username_mismatch = true;
auth_only = true;
selector = "dkim";
sign_local = true;
symbol = "DKIM_SIGNED";
try_fallback = true;
use_domain = "header";
use_esld = false;
use_redis = false;
hash_key = "DKIM_KEYS";
domain {
    sub.domain.tld {
        path = "/path/to/dkim/key";
        selector = "mail";
    }
}
```
But I don't like having disabled some important default options in `local.d/dkim_signing.conf` ie `allow_hdrfrom_mismatch = true;`

**Comment by fatalbanana** [comment] 2017-04-12 09:03
@dehnli would it help your case if parent domain could optionally be considered a match (WRT usernames & header vs envelope)? I have a patch that enables this.

**Comment by mundschenk-at** [comment] 2017-04-23 10:07
@fatalbanana Would it be possible to make the setting `use_domain` overridable for local and `sign_networks` as well? I've a separate virtual host for mailing lists (where `From:` remains the original sender) I'd like to sign for the list address in the envelope.

Also, I've noticed that `sign_networks` is not checked if it's a local address, so it's not possible use that to override settings applying to all local networks. It would be nice, if we could use this to generate more specific rules.

**Comment by fatalbanana** [comment] 2017-04-26 14:26
@leenooks yes; DKIM signing with rspamd implies [scanning outbound](https://rspamd.com/doc/tutorials/scanning_outbound.html); you can disable unwanted checks and/or rescore actions/symbols with [settings module](https://rspamd.com/doc/configuration/settings.html).

@mundschenk-at I've added `use_domain_sign_networks` and `use_domain_local` settings (where the former will take precedence over the latter).

**Comment by mundschenk-at** [comment] 2017-04-26 14:51
Thank you!

**Comment by fatalbanana** [comment] 2017-05-02 15:36
Seems to be a duplicate of https://github.com/vstakhov/rmilter/issues/177

**Closed by fatalbanana** 2017-05-02 15:36 UTC
