### ISSUE TITLE
multimap regexp failed

### ISSUE THREAD

**Issue by jirireischig** [vstakhov/rspamd#1164] opened 2016-11-22 12:05 UTC
I try use multimap with regexp enabled but it fails in rspamd 1.4.0.

I try example:

`# local.d/multimap.conf`
`SENDER_FROM_WHITELIST {`
`  type = "from";`
`  map = "file:///tmp/from.map";`
`  regexp = true;`
`}`

and in file /tmp/from.map:

`# Sole key`
`/example\d+\.com/i`
`# Key + value (test)`
`/other\d+\.com/i test`
`# Comments are still enabled`

Rspamd crashing continuosly.

see log entry:

Nov 22 12:50:50 ecn3.ecn.cz rspamd[22056]: (main) <2594ed>; main; rspamd_cld_handler: normal process 22426 terminated abnormally by signal: 4 but NOT created core file

**Comment by vstakhov** [comment] 2016-11-22 12:09
It seems you have incompatible CPU for this.

**Comment by jirireischig** [comment] 2016-11-22 12:19
What CPU is compatible for it.
I use AMD.

**Comment by vstakhov** [comment] 2016-11-22 12:25
Please paste full information about your cpu (could be found in `/proc/cpuinfo` on Linux). I've not tested AMD cpus at all, but SIGILL means that hyperscan doesn't like your CPU. Intel Core2 is minimum supported.

**Comment by jirireischig** [comment] 2016-11-22 12:47
cat /proc/cpuinfo 
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 15
model           : 107
model name      : AMD Athlon(tm) 64 X2 Dual Core Processor 5200+
stepping        : 2
cpu MHz         : 1000.000
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch lbrv
bogomips        : 1994.95
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp tm stc 100mhzsteps

**Comment by vstakhov** [comment] 2016-11-22 12:48
Yes, it lacks `ssse3` instructions set which is unfortunately required for hypercan.

**Comment by jirireischig** [comment] 2016-11-22 12:53
OK, but older version Rspamd 1.3.5 was working without problem.
Is it possible to make new version compatible with oldest CPU?

**Comment by vstakhov** [comment] 2016-11-22 13:36
In fact, hyperscan should be disabled on such CPU. Can you provide stack trace for this error? https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed

**Comment by jirireischig** [comment] 2016-11-22 15:01
You can download coredump of crashed rspamd:
http://ecn.cz/core-rspamd-sig4-user978-group978-pid6283-time1479826322.gz

**Comment by vstakhov** [comment] 2016-11-22 15:03
Could you please call gdb for this core? Like:

gdb /usr/bin/rspamd /corefile

gdb> bt

And show me the trace.

**Comment by jirireischig** [comment] 2016-11-22 15:06
(gdb) bt
#0  0x00000000006643e6 in hwlmExec ()
#1  0x0000000000686e4f in roseBlockExec ()
#2  0x00000000006609d6 in hs_scan ()
#3  0x0000000000475455 in rspamd_match_regexp_map ()
#4  0x00000000004a6f08 in lua_map_get_key ()
#5  0x00007f3fc3f00328 in luaD_precall () from /lib64/liblua-5.1.so
#6  0x00007f3fc3f0ae7f in luaV_execute () from /lib64/liblua-5.1.so
#7  0x00007f3fc3f0073d in luaD_call () from /lib64/liblua-5.1.so
#8  0x00007f3fc3effa6e in luaD_rawrunprotected () from /lib64/liblua-5.1.so
#9  0x00007f3fc3f008ca in luaD_pcall () from /lib64/liblua-5.1.so
#10 0x00007f3fc3efc44d in lua_pcall () from /lib64/liblua-5.1.so
#11 0x000000000048ce97 in lua_metric_symbol_callback ()
#12 0x00000000004c7c1f in rspamd_symbols_cache_check_symbol.isra.4 ()
#13 0x00000000004c90e1 in rspamd_symbols_cache_process_symbols ()
#14 0x00000000004cb47f in rspamd_task_process ()
#15 0x00000000004cb649 in rspamd_task_process ()
#16 0x00000000004cb649 in rspamd_task_process ()
#17 0x00000000004cb649 in rspamd_task_process ()
#18 0x00000000004487d9 in rspamd_worker_body_handler ()
#19 0x000000000046c4f6 in rspamd_http_on_message_complete ()
#20 0x000000000090f1dd in http_parser_execute ()
#21 0x000000000046deb7 in rspamd_http_event_handler ()
#22 0x00007f3fc5785a14 in event_base_loop () from /lib64/libevent-2.0.so.5
#23 0x000000000044804c in start_worker ()
#24 0x00000000004d111e in rspamd_fork_worker ()
#25 0x0000000000446866 in rspamd_fork_delayed_cb ()
#26 0x00007f3fc5785a14 in event_base_loop () from /lib64/libevent-2.0.so.5
#27 0x000000000043b890 in main ()

**Comment by vstakhov** [comment] 2016-11-22 15:09
Thanks, the issue is clear to me now.

**Comment by vstakhov** [comment] 2016-11-22 15:18
It should be fixed now, thanks for report.

**Comment by jirireischig** [comment] 2016-11-23 07:38
Thanks for your fix.
Do you known, when do you release new version with this fix?

**Closed** 2017-02-17 14:04 UTC
