### ISSUE TITLE
Problem with SPF

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#215] opened 2015-03-12 08:11 UTC
Rspamd 0.8.2

Message:
Authentication-Results: ip=95.211.146.161:54788, host=, helo=relay.habramail.net, mailfrom=noreply@megamozg.ru
From: Megamozg <noreply@megamozg.ru>
X-Spam-Result: R_SPF_SOFTFAIL(1.50)

IP 95.211.146.161 exists in SPF.
Symbol R_SPF_SOFTFAIL exists.

-----------------------------------------
dig txt megamozg.ru
megamozg.ru.         IN      TXT     "v=spf1 include:spf.habramail.net include:aspmx.googlemail.com ~all"

dig txt spf.habramail.net
spf.habramail.net.   IN      TXT     "v=spf1 redirect=_spf.habramail.net"

dig txt _spf.habramail.net
_spf.habramail.net.  IN      TXT     "v=spf1 ip4:82.192.95.169/32 ip4:95.211.146.161 ip6:2001:1af8:4010:a087:22::169 ?all"

**Comment by vstakhov** [comment] 2015-03-18 11:56
I cannot reproduce your error:

    rspamc -i 95.211.146.161 -F 'noreply@megamozg.ru'

gives me `R_SPF_ALLOW` symbol being added.

**Comment by vstakhov** [comment] 2015-03-25 13:12
It's fixed in master branch but the fix won't be backported to the 0.8 branch due to massive incompatibilities. However, if somebody wants to handle that task I have nothing against it :)

**Closed** 2015-05-09 21:09 UTC
