### ISSUE TITLE
questions about web history

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rspamd#407] opened 2015-10-23 06:08 UTC
1) How change max history rows? Now max 200 rows only.
2) How can I reset web history from cli? Like "Reset" from from web.
3) Is it possible mark "actions" different colors?  Now all actions is orange.
4) Is it possible to export history?

Thanks.

**Comment by vstakhov** [comment] 2015-10-23 15:45
1) It is fixed for now
2) You cannot do it so far, I'm afraid
3) They should have different colors, could you show me a sample?
4) The answer is "no" as for (2). But the support in rspamc CLI should be trivially added

**Comment by moisseev** [comment] 2015-10-23 17:36
3) rspamd 1.0.6 - all actions in one color.
![2015-10-23 20_26_14-rspamd web interface - pale moon](https://cloud.githubusercontent.com/assets/2275981/10700160/83439b96-79c4-11e5-9641-5c450690c373.png)
BTW `rspamd_protocol_http_reply` in the log has `from` field. Do you plan to add it to the history?

**Comment by mnik247** [comment] 2015-10-23 20:22
to moisseev - I have same colors with 1.0.6

**Comment by mnik247** [comment] 2015-10-23 20:26
to vstakhov
>3) They should have different colors, could you show me a sample?
Now only one - example above from moisseev
>4) The answer is "no" as for (2). But the support in rspamc CLI should be trivially added
If possible add support "export history" to rspamc.

**Comment by vstakhov** [comment] 2015-10-23 22:35
I've fixed coloring, thanks!

**Comment by vstakhov** [comment] 2015-10-23 22:41
Adding/removing stuff to history is hard. It was intended by my initial view for merely web interface. For all CLI and other stuff there is logging system. Therefore, any change in history would break backward compatibility and a more recent rspamd will not be able to read history written by an older version. I don't like to break backward compatibility or do code bloat by supporting of legacy format just to have two separate approaches to the same task.

**Comment by moisseev** [comment] 2015-10-24 05:41
I'm afraid it has got to be done in order to implement https://github.com/vstakhov/rspamd/issues/286. Web UI authentication without filtering by sender or recipient makes no sense. Furthermore MID or IP means nothing for majority of mail users. If they will be unable to identify messages in history then history will be useless for them.

History format might be converted during upgrade, but I don't think keeping web history during such a major upgrade is critical.

**Comment by vstakhov** [comment] 2015-10-24 12:13
What has to be done? Adding `from` or moving towards flexible history format?

**Comment by mnik247** [comment] 2015-10-24 12:51
I think "flexible history format" is best way

**Comment by moisseev** [comment] 2015-10-24 13:41
_to vstakhov_
I mean adding sender and recipient actually.
I believe authentication to the web UI implies restricted access for some users. I.e. restricted users should see only messages related to them. Some condition should be used to hide other messages from them, for instance if web UI authenticated user name doesn't match sender or recipient. For now the history doesn't contain data to decide which message should be hidden from particular user.

> "flexible history format"

Do you mean just flexible UI representation? I think hiding some history columns is pointless. 
If you mean flexible history storage format, I don't like th idea.  In the future it would be a source of difficulties with potential features that depend on history.

**Comment by vstakhov** [comment] 2015-10-24 20:03
I'm going to switch storage format to json very soon. Any objections?

**Comment by moisseev** [comment] 2015-10-24 21:13
No objections. It's reasonable. I got  "flexible" and "configurable" mixed up.

**Comment by vstakhov** [comment] 2015-11-28 23:35
Done

**Closed by vstakhov** 2015-11-28 23:35 UTC
