### ISSUE TITLE
Cannot Upgrade Bayes Schemas On Redis

### ISSUE THREAD

**Issue by TheDarkula** [vstakhov/rspamd#2078] opened 2018-03-15 01:44 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0

### Operation system, CPU, memory and environment:
Arch linux, intel core i5, 16GB

### Description (Please provide a descriptive summary of the issue):
Cannot upgrade redis BAYES_HAM/BAYES_SPAM schemas.

Also, there is a typo in the suggested command to use:
`rspamd_redis_parse_classifier_opts: you are using old bayes schema for redis statistics, please consider converting it to a new one by using 'rspamadm configwizard statistics'`
should be:
`rspamd_redis_parse_classifier_opts: you are using old bayes schema for redis statistics, please consider converting it to a new one by using 'rspamadm configwizard statistic'`

### Steps to reproduce:
run rspamadm configwizard statistic

### Expected results:
Redis schema will be upgraded

### Actual results:
Nothing is done.

### Additional information:
Thanks so much for making rspamd. It's amazing. :)

**Comment by fatalbanana** [comment] 2018-03-15 10:31
`rspamadm configwizard statistic` (without trailing 's') should work.

Should be fixed in [this commit](https://github.com/vstakhov/rspamd/commit/f73dba9e823e4e806c66d5ae4d660172acd371cc)

**Comment by TheDarkula** [comment] 2018-03-15 15:46
It looks like that fixes the typo, but does it fix the issue of not upgrading the schemas?

**Comment by WRMSRwasTaken** [comment] 2018-03-17 12:44
Running the command (without the typo) did convert the bayes schema for me. However, after the config wizard added `local.d/classifier-bayes.conf` with the content
```
new_schema = true;
expire = 31536000;
```
rspamd still complained about using the old bayes schema on startup. What solved this for me is adding those 2 options in `local.d/statistic.conf`.

However, I can't say if the conversion worked successfully.

**Comment by RvdE** [comment] 2018-03-17 16:58
I've upgraded to 1.7.0 as well, but running rspamadm configwizard statistic told me 0 elements were converted for both BAYES_HAM and BAYES_SPAM. After some investigation it seems the rspamadm command doesn't take the database you've set from statistic.conf into account (mine was set to "1"). After moving the keys from db 1 to db 0, rerunning the command worked as it should.

However, the created local.d/classifier-bayes.conf doesn't work as intended and I also had to add the two lines from that file to my local.d/statistic.conf

**Comment by WRMSRwasTaken** [comment] 2018-03-17 17:00
Hmm, the issue with the redis database seems to be related to my ticket: https://github.com/vstakhov/rspamd/issues/2083

**Comment by hardware** [comment] 2018-03-17 23:13
Redis statistics configuration since 1.7 definitely needs some clarification i think. And `local.d/classifier-bayes.conf`doesn't work as intended when `local.d/statistic.conf`already exists. 

> the issue with the redis db setting seems to be related to my ticket

It explain why my 1.7 configuration example here : https://github.com/vstakhov/rspamd.com/issues/319 only works when redis db equal to 0.

**Comment by WRMSRwasTaken** [comment] 2018-03-17 23:38
The upgrade wizard also ignores the 
```
read_servers = "127.0.0.1:6379";
write_servers = "10.8.0.1:6379";
```
configuration.

**Comment by TheDarkula** [comment] 2018-04-11 20:14
I've tried everything that everyone has suggested. My redis database is db0, so it isn't that issue. In local.d/redis.conf, I have `servers = "/run/redis/redis.sock";`
Does the fact that I'm using a unix socket have anything to do with it?

**Comment by pipiche38** [comment] 2018-04-27 09:15
Funny enough, I have been able to do the convertion by removing the db = "16" in the local.d/redis.conf configuration file !

**Comment by vstakhov** [comment] 2018-04-27 10:26
It is configured in Redis:

```
# Set the number of databases. The default database is DB 0, you can select
# a different one on a per-connection basis using SELECT <dbid> where
# dbid is a number between 0 and 'databases'-1
databases 16
```

**Closed** 2018-06-25 14:07 UTC
