### ISSUE TITLE
url:is_phished(): mixed charset URLs FP (punycode)

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#842] opened 2016-08-12 07:20 UTC
An URL is treated as phished if the hostname part has different charsets.

``` html
Content-Type: text/html; charset=utf-8

<a href="http://www.xn----7sbbahae8ad1abf0b3e8g.xn--p1ai">http://www.главзвук-казань.рф</a>
```

PHISHING(4.00)[главзвук-казань.рф->xn----7sbbahae8ad1abf0b3e8g.xn--p1ai]

**Comment by fatalbanana** [comment] 2016-09-09 09:04
Duplicate of #337

**Comment by moisseev** [comment] 2017-02-25 08:48
Symbol: PHISHING (0.14)[центрконсалт.рф->xn--80ajpfhbgomfh1b.xn--p1ai]
```html
<span lang="EN-US"><a href="http://xn--80ajpfhbgomfh1b.xn--p1ai/post/568/" target="_blank" class="underline">www<span lang="RU">.центрконсалт.рф</span></a></span>
```
[phishing-idn-fp.zip](https://github.com/vstakhov/rspamd/files/801030/phishing-idn-fp.zip)

I am not sure if it is IDNA related or just HTML elements grouping issue.

**Comment by moisseev** [comment] 2017-02-25 08:56
The `PHISHING` symbol score is too low for this sample:
```
# rspamc /home/moiseev/phishing-low.eml
Results for file: /home/moiseev/phishing-low.eml (0.473 seconds)
...
Symbol: PHISHING (0.29)[сочи-отдыхуморя.рф->sochi-krugovaya18a.ru]
...
```
[phishing-low.zip](https://github.com/vstakhov/rspamd/files/801042/phishing-low.zip)

**Comment by vstakhov** [comment] 2017-02-25 12:25
The first case is missing esld checks. I'll fix it. The second case is more tricky as there is heuristic to find out how far are displayed and href urls. This heuristic exists because the Internet is full of retarded senders (e.g. sendgrid) who just replace URLs with their own redirectors. However, we can penalise idn and non-idn labels in this rule...

**Comment by moisseev** [comment] 2017-02-26 08:22
Now there is no `PHISHING` symbol  but `R_MIXED_CHARSET (15.00)` for [phishing-idn-fp.zip](https://github.com/vstakhov/rspamd/files/801030/phishing-idn-fp.zip) sample.
```
2017-02-26 11:19:30 #97414(normal) <8dc3e5>; chartable; rspamd_chartable_process_word_utf: word www.центрконсалт.рф, badness: 3.00
```

**Closed** 2017-02-26 16:24 UTC
