### ISSUE TITLE
[WebUI] widgets on Status page not updating/refreshing

### ISSUE THREAD

**Issue by lymon66** [vstakhov/rspamd#1353] opened 2017-01-19 08:52 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd 1.4.3

### Description (Please provide a descriptive summary of the issue):
WebUI widgets on the main Status page are not updated when clicking "refresh"
Only filter stats pie refreshes

The widgets only seem to refresh when logging out (Disconnect) and then log in again.

### Additional information:
Tried and tested with different browsers

**Comment by vstakhov** [comment] 2017-01-19 09:02
Duplicate of #1285.

**Closed by vstakhov** 2017-01-19 09:02 UTC
