### ISSUE TITLE
Rspamd and Exim "Connection reset by peer"

### ISSUE THREAD

**Issue by Twilek-de** [vstakhov/rspamd#430] opened 2015-11-21 15:00 UTC
I am trying to use Rspamd (1.0.10) with Exim (4.86). I have implemented the options as posted in the Wiki. When a new message comes in Exim log will show:

2015-11-21 15:53:18 1a09XS-0004jF-Ht spam acl condition: error reading from spamd socket: Connection reset by peer
2015-11-21 15:53:18 1a09XS-0004jF-Ht H=mout.gmx.net [212.227.17.21] Warning: ACL "warn" statement skipped: condition test deferred

Rspamd log will show
(normal) <06859d>; task; accept_socket: accepted connection from ::ffff:127.0.0.1 port 44402
(normal) <06859d>; task; rspamd_message_parse: loaded message; id: <trinity-2fe66e10-3e6a-4c3a-9beb-65aecae8b3ef-1448117443853@3capp-gmx-bs55>; queue-id: <1a09Uy-0004dC-6i>
(normal) <06859d>; task; lua_metric_symbol_callback: call to (HTML_SHORT_LINK_IMG_1) failed: /usr/share/rspamd/rules/html.lua:32: attempt to index local 'hc' (a nil value); trace: [1]:{/usr/share/rspamd/rules/html.lua:32 - <unknown> [Lua]};
(normal) <06859d>; task; lua_metric_symbol_callback: call to (R_EMPTY_IMAGE) failed: /usr/share/rspamd/rules/html.lua:82: attempt to index local 'hc' (a nil value); trace: [1]:{/usr/share/rspamd/rules/html.lua:82 - <unknown> [Lua]};
(normal) <06859d>; task; rspamd_protocol_http_reply: id: <trinity-2fe66e10-3e6a-4c3a-9beb-65aecae8b3ef-1448117443853@3capp-gmx-bs55>, qid: <1a09Uy-0004dC-6i>, ip: 212.227.15.19, from: xxx@xxx.de, (default: F (no action): [0.39/15.00] [RCVD_IN_DNSWL_LOW,MIME_HTML_ONLY,HFILTER_MID_NOT_FQDN,R_SPF_ALLOW,RWL_MAILSPIKE_POSSIBLE]), len: 1689, time: 1014.103ms real, 14.551ms virtual, dns req: 23,
(normal) <c9675d>; task; accept_socket: accepted connection from ::ffff:127.0.0.1 port 44674
(normal) <c9675d>; task; rspamd_worker_error_handler: abnormally closing connection from: ::ffff:127.0.0.1, error: IO timeout

I have installed rspamd via the openbuild service for Debian stretch. Any Ideas what is going wrong?

**Comment by Twilek-de** [comment] 2015-12-09 17:27
My exim paniclog looks like this:

2015-12-08 17:57:51 1a6LaJ-0006j9-8E spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-08 18:27:40 1a6M3A-0007Yj-2I spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-08 19:54:41 1a6NPN-00027g-54 spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-08 20:01:51 1a6NWI-0002q2-G8 spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-08 20:08:48 1a6Nd1-0002xb-UG spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-08 20:30:12 1a6Nxk-0003TQ-Mq spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-08 20:36:06 1a6O3S-0003iI-Es spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-08 20:47:53 1a6OEr-00040I-DL spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 00:16:32 1a6RUl-0000wt-Hx spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 00:27:21 1a6RfE-0001Ad-S5 spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 02:23:17 1a6TTQ-00042f-Qb spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 02:28:34 1a6TYX-00049c-Ts spam acl condition: Connection reset by peer on spamd socket
2015-12-09 02:33:52 1a6Tdf-0004HC-TF spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 03:08:40 1a6UBM-0005A6-60 spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 04:44:06 1a6Vfh-0007Om-Ag spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 05:02:46 1a6Vxm-0007qL-9m spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 05:41:35 1a6WZL-0000Oe-Ow spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 08:04:59 1a6Yo7-0003ls-F6 spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 08:53:29 1a6ZZ2-0004z9-Ei spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 10:09:31 1a6akd-0006jH-QD spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 10:55:21 1a6bSy-0007qn-Af spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 11:00:52 1a6bYK-00081H-5n spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 11:01:13 1a6bYe-00081a-IY spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 11:15:25 1a6bmO-0008NL-H4 spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 11:34:15 1a6c4c-0000It-Tu spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 15:38:02 1a6fsY-0006BK-AD spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 15:50:20 1a6g4R-0006VG-Uj spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 15:54:17 1a6g8G-0006Zd-9U spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 16:15:18 1a6gSc-0007CL-9J spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 17:14:42 1a6hO5-0000Aj-JB spam acl condition: error reading from spamd socket: Connection reset by peer
2015-12-09 17:25:18 1a6hYL-0000TE-I1 spam acl condition: error reading from spamd socket: Connection reset by peer

Does anyone have an idea where this error might come from?

**Comment by Twilek-de** [comment] 2015-12-09 19:09
As far as I can see it is not every message, but I have not figured out with which message it exactly fails. I used the opensuse build service with the package 1.0.10+nmu1 build for Debian 8.0. I am afraid analysing a raw tcp stream is a bit above my technical horizon.

**Comment by fatalbanana** [comment] 2015-12-09 19:24
The communication should be fairly easy to interpret fwiw, see https://rspamd.com/doc/architecture/protocol.html - Exim uses the legacy RSPAMC protocol.

If it happens on certain mails only, you may try getting copies of these & trying scanning with `rspamc` or the web interface.

You have installed binaries for Debian `jessie` but you are using `stretch`? I would recommend rather rebuilding the source package for your OS (unpack the tarball and do `dpkg-buildpackage -us -uc` in `rspamd-1.0.10` directory).

**Comment by Twilek-de** [comment] 2015-12-09 20:13
I build a package and installed it. The first emaile passed, the second gave a connection reset. Manually entering the mail into rspamd via the webinterface scans the contant without error.

**Comment by Twilek-de** [comment] 2015-12-09 20:34
I used tcpflow. As far as I can see the mails a delivered to rspamd without a problem:

CHECK RSPAMC/1.3
Content-length: 1826
Queue-Id: 1a6lHK-0005rS-KN
From: <xxx@gmail.com>
Recipient-Number: 1
Rcpt: <xxx@xxx.de>
Helo: mail-lf0-f47.google.com
Hostname: mail-lf0-f47.google.com
IP: 209.85.215.x

From xxx@gmail.com Wed Dec 09 21:23:59 2015
X-Envelope-From: <xxx@gmail.com>
X-Envelope-To: xxx@xxx.de
Received: from mail-lf0-f47.google.com ([209.85.215.47])
        by www.xxx.de with esmtps (TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128)
        (Exim 4.86)
        (envelope-from <xxx@gmail.com>)
        id 1a6lHK-0005rS-KN
        for xxx@xxx.de; Wed, 09 Dec 2015 21:23:59 +0100
Received: by lfaz4 with SMTP id z4so42707832lfa.0
        for <xxx@xxx.de>; Wed, 09 Dec 2015 12:23:57 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:date:message-id:subject:from:to:content-type;
        bh=h3EzCK4ewNSJdD8JX+9Wns+JXMT1ja+Y93VM5Lxp/3Q=;
        b=APoMTnzxPUI4EeEVvuFnHLrkmUrMK0SxDvHV/lYZpCEc+Mr2YzYOJTkXrv0QeIBr6s
         J+8S/wa8ecsBPxI23oxosEAvyR99gNLKdH7FoJGiV5Bk5vqJSuQme4uxuGUwHTkOVFDp
         PWpHpAKxsVjU9jY7aXYKr3bGOHlKCiZQJcwm3IpIV+GPZir+KIBNSPnKIDVAekkVrU6u
         ssMq2eCDciOioefrMKhem1reNN/HCtOu6gf8HsaddbC3EI5xrE8mBEh7G7JC8tx79mma
         TnDvByBdNKs8lDZtrvKjyGcdGWTTfuM674Fxd1kvWkqyLezRz4Jh6If2kou/zQuYQ7Wf
         B5fg==
MIME-Version: 1.0
X-Received: by 10.25.x.x with SMTP id u192mr3496780lfd.14.1449692637145;
 Wed, 09 Dec 2015 12:23:57 -0800 (PST)
Received: by 10.25.134.139 with HTTP; Wed, 9 Dec 2015 12:23:57 -0800 (PST)
Date: Wed, 9 Dec 2015 21:23:57 +0100
Message-ID: <CA+Msx6+cv3+S0-kLz-fBJ0ZyjyyFyWxVDSxwS9r8H+z8Xj=EMQ@mail.gmail.com>
Subject: Test 2
From: x <x@gmail.com>
To: "x" <xxx@xxx.de>
Content-Type: multipart/alternative; boundary=001a11401576abb46305267cde7f

--001a11401576abb46305267cde7f
Content-Type: text/plain; charset=UTF-8



--001a11401576abb46305267cde7f
Content-Type: text/html; charset=UTF-8

<div dir="ltr"><br></div>

--001a11401576abb46305267cde7f--

This is the actual mail that failed. It does not show up in the Rspamd history as being scanned.

**Comment by fatalbanana** [comment] 2015-12-09 21:00
Response from the server is of particular interest here- tcpflow will create a file for the other end of the connection (`y-x` where file you identified is `x-y`).

**Comment by Twilek-de** [comment] 2015-12-09 22:44
When the scanning succeds there is a response like

RSPAMD/1.3 0 EX_OK
Metric: default; False; -2.20 / 15.00 / 0.0
Action: no action
Symbol: HFILTER_MID_NORES_A_OR_MX(0.50)
Symbol: R_DKIM_ALLOW(-1.10)
Symbol: DMARC_POLICY_ALLOW(-0.50)
Symbol: RWL_MAILSPIKE_POSSIBLE(0.00)
Symbol: R_SPF_ALLOW(-1.10)
Message: (SPF): spf allow
Message-ID: CA+Msx6LegqfRKXbsd1uKX4hKzJkeZyNo5QZr6sf9Dr_Jf2nTWg@mail.gmail.com

When the timeout occurs there is no response from rspamd. So the message is sent to rspamd but the daemon does not respond at all.

**Comment by ilyakruchinin** [comment] 2015-12-23 05:24
Same issue here. Ubuntu 15.10 with rspamd 1.0.10.
Using 8 "normal" workers, listening on 127.0.0.1 11333 I am getting about 1 such message per minute (with about 10 messages per minute throughput).
I believe it was less when I only had 2 "normal" workers.

**Comment by fatalbanana** [comment] 2015-12-23 10:48
Would be interesting to see rspamd logs relating to a failed scan if you can identify them (hex numbers in angle brackets can be used) and to have an indication of how long the scan took & what was sent/received (Lua errors in the OP are a bit mysterious to me- do you have those too?).

Please try 1.0.11 or the nightly build- there are packages for wily @ rspamd.com.

**Comment by ilyakruchinin** [comment] 2015-12-23 22:23
Upgraded rspamd to 1.0.11. Same issue with 8 normal worker processes.
Can't get the logs as /var/log/rspamd is empty.
I don't use any Lua processing.
Will now revert back to using only 2 normal worker processes (as it seems to be less of an issue with less workers).

**Comment by ilyakruchinin** [comment] 2015-12-23 22:44
Found logs in journald:
This is the log entry that corresponds to the issue:
Dec 24 09:39:27 rspamd rspamd[40443]: (normal) <e0a56e>; task; accept_socket: accepted connection from ::ffff:127.0.0.1 port 54866
Dec 24 09:39:27 rspamd rspamd[40443]: (normal) <e0a56e>; task; rspamd_worker_error_handler: abnormally closing connection from: ::ffff:127.0.0.1, error: IO timeout
Dec 24 09:39:44 rspamd rspamd[40443]: (normal) <e1bbc4>; task; accept_socket: accepted connection from ::ffff:127.0.0.1 port 54874
Dec 24 09:39:44 rspamd rspamd[40443]: (normal) <e1bbc4>; task; rspamd_worker_error_handler: abnormally closing connection from: ::ffff:127.0.0.1, error: IO timeout
Dec 24 09:39:56 rspamd rspamd[40443]: (normal) <6a0659>; task; accept_socket: accepted connection from ::ffff:127.0.0.1 port 54886
Dec 24 09:39:56 rspamd rspamd[40443]: (normal) <6a0659>; task; rspamd_worker_error_handler: abnormally closing connection from: ::ffff:127.0.0.1, error: IO timeout

I can confirm that if I remove "count = 8;" from worker-normal.inc, then rspamd only uses 2 normal worker processes and the issue becomes much LESS frequent (but not totally gone).

**Comment by ilyakruchinin** [comment] 2015-12-23 23:44
I've enabled debug log, but couldn't find anything that would pinpoint the issue.
This is a little odd, though:
Dec 24 10:29:38 rspamd systemd-journal[236]: Suppressed 7975 messages from /system.slice/rspamd.service
Dec 24 10:30:08 rspamd systemd-journal[236]: Suppressed 13840 messages from /system.slice/rspamd.service
Dec 24 10:30:39 rspamd systemd-journal[236]: Suppressed 12693 messages from /system.slice/rspamd.service
Dec 24 10:31:09 rspamd systemd-journal[236]: Suppressed 3482 messages from /system.slice/rspamd.service
Dec 24 10:31:39 rspamd systemd-journal[236]: Suppressed 5040 messages from /system.slice/rspamd.service
Dec 24 10:32:14 rspamd systemd-journal[236]: Suppressed 27829 messages from /system.slice/rspamd.service

**Comment by crepererum** [comment] 2016-01-27 10:01
@ilyakruchinin that seems to be a polite reminder of journald (the log daemon) that rspamd is emitting too many messages and that it suppressed some of them to avoid flooding your log files.

I'm using rspamd in a different setup (`rspamc --mime` as a sieve filter) and I'm experiencing the same issues ("connection reset by peer"). So for some reason, the rspamd seems to close the connection which is created by the client. This log entries seem to be interesing:
```
Jan 27 09:46:08.973971 ▓▓▓▓.net rspamd[▓▓▓▓]: (normal) <acd0fa>; task; accept_socket: accepted connection from 127.0.0.1 port 38894
Jan 27 09:46:08.974671 ▓▓▓▓.net rspamd[▓▓▓▓]: (normal) <acd0fa>; task; rspamd_worker_error_handler: abnormally closing connection from: 127.0.0.1, error: IO timeout
```
Why is this a timeout? The time from `accept` to `timout` is very short.

**Comment by elopez** [comment] 2016-06-24 11:28
I'm still seeing this problem with rspamd 1.2.8-1~xenial and exim4 4.86.2-2ubuntu2 on Ubuntu xenial. I'm now trying the workaround described in https://fmos.at/2016/02/10/interoperating-exim-with-rspamd/ but a proper solution would be best. Let me know if I can be of help debugging this.

**Comment by vstakhov** [comment] 2016-06-24 13:21
Exim should not use rspamc protocol. Exim should not use `shutdown` call (https://bugs.exim.org/show_bug.cgi?id=1802). However, exim developers don't want to care about rspamd. So my question is: why should I care about exim? In the case you've described the issue looks different - I'm not sure that it's not an issue with socket activation and systemd. Could you reproduce it on some systemd-less distributive (e.g. Ubuntu trusty)?

**Comment by vstakhov** [comment] 2016-06-24 13:57
Well, it's not related to exim, but I suppose it is related to systemd somehow.

**Comment by elopez** [comment] 2016-06-24 16:09
I have another system running Debian (without systemd) with rspamd 1.2.7-1~jessie and exim 4.87-3 and this issue doesn't seem to occur there, so it may indeed be related to systemd activation.

**Comment by vstakhov** [comment] 2016-06-24 16:11
The problem is that I can't understand how that happens and it drives me nuts.

**Comment by elopez** [comment] 2016-06-26 18:28
The previous workaround didn't solve the issues completely, so I have now tried disabling `rspamd.socket`, enabling `rspamd.service` and editing the rspamd config as follows:

```
$ grep -r . /etc/rspamd/override.d/
/etc/rspamd/override.d/worker-normal.inc:bind_socket = "localhost:11333";
/etc/rspamd/override.d/worker-controller.inc:bind_socket = "localhost:11334";
```

So far it has been working fine.

**Comment by vstakhov** [comment] 2016-06-27 09:19
I think I'll just disable socket activation since it is broken completely.

**Comment by vstakhov** [comment] 2016-06-27 09:52
Or maybe the issue is that systemd passes sockets in blocking mode and rspamd does not set it to non-blocking mode.

**Comment by vstakhov** [comment] 2016-06-27 09:57
Could you please check if it is fixed with this commit?

**Closed** 2016-08-18 15:46 UTC

**Comment by Phyks** [comment] 2016-12-13 13:36
I can see similar output in my logs with Debian Jessie and rspamd 1.4.1-2~jessie. I am not using Exim but Postfix (which seems to confirm this issue is actually systemd related and not due to exim). Still, the above mentionned commit should have been integrated in the 1.4.1 release I think, and I am not sure whether this issue should actually not be considered as closed, or if I am experimenting an entirely new issue.

If needed, the typical logline I see is:
```
rspamd[11861]: (normal) <XXX>; task; accept_socket: accepted connection from ::1 port 43832, task ptr: XXXXXXXXX
```

Thanks

**Comment by fatalbanana** [comment] 2016-12-13 13:40
Systemd socket activation was removed. Maybe process crashed or rspamd was shut down during scan, `grep XXX` should show more logs; if it crashed you should have messages from `cld_handler`.

**Comment by Phyks** [comment] 2016-12-13 14:44
Sorry, my copy-paste missed a line in my last message, I edited accordingly.

`grep XXX` only gives these two output lines in the log. I could not see any `cld_handler` message in the logfile (logging was at default log level `info` when I first noticed it, I did not yet reproduced it with a higher log level).

**Comment by fatalbanana** [comment] 2016-12-13 14:50
Possibly some monitoring script connects to rspamd and closes connection.

Do you see anything going wrong in rmilter log?

**Comment by Phyks** [comment] 2016-12-13 15:35
No, everything looks perfect in `rmilter` log at the same time. :/

**Comment by filipisaci** [comment] 2017-08-16 13:04
Peguei esta situação, e o meu problema estava relacionado à hora do servidor, devido ao offset do relógio com o UTC, é apresentado o erro na verificação do certificado SSL.
-----
I took this situation, and my problem was related to the server time, due to the clock offset with UTC, the error in the SSL certificate verification is displayed.
