### ISSUE TITLE
Rspamd is silently ignoring config files that it can not access

### ISSUE THREAD

**Issue by fkrauthan** [vstakhov/rspamd#1996] opened 2018-01-22 08:17 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
Ubuntu 16.04 on a Vagrant Virtual machine with 1GB RAM

### Description (Please provide a descriptive summary of the issue):
I configured the system to use unix sockets for the worker-controller as well as the worker-proxy (which is in local milter mode). But no unix sockets are created event tho all checks are working

### Compile errors (if any):
None

### Steps to reproduce:
Configure worker-controller and worker-proxy to use unix sockets. Set permission of config file to be read only by root. No access by group or everyone. Start rspamd as a user (e.g. _rspamd)

### Expected results:
Rspamd is giving me a error message or warning that it can not read some files in local.d.

### Actual results:
The service starts up with default configs instead of giving me any warning/error in the logfile that it was not able to open some/all config files.

### Configuration:

The worker part out of the `rspamadm configdump` call
```
worker {
    bind_socket = "*:11333";
    type = "normal";
    mime = true;
    task_timeout = 8.0;
    enabled = false;
}
worker {
    bind_socket = "/run/rspamd/worker-controller.socket mode=0660 owner=_rspamd group=www-data";
    type = "controller";
    count = 1;
    password = "$2$paparrytknfm8...";
    secure_ip = "127.0.0.1";
    secure_ip = "::1";
    static_dir = "/usr/share/rspamd/www";
    enable_password = "$2$paparrytknfm8...";
}
worker {
    rspamd_proxy {
        bind_socket = "/run/rspamd/worker-proxy.sock mode=0660 owner=_rspamd group=postfix";
        type = "proxy";
        milter = true;
        timeout = 120.0;
        upstream {
            local {
                default = true;
                hosts = "localhost";
                self_scan = true;
            }
        }
        count = 1;
    }
}
```

The `rspamadm configtest` output to proof that the config in general seem to be ok:

```
2018-01-22 08:16:32 #19184(configtest) <h4udjg>; symcache; rspamd_symbols_cache_validate: symbol 'SPOOFED_SENDER' has its score defined but there is no corresponding rule registered
syntax OK
```

**Comment by stephdl** [comment] 2018-01-30 20:17
no familiar with ubuntu but what are the unix permission on  /run/rspamd

**Comment by fkrauthan** [comment] 2018-01-31 04:43
Belongs to user and group `_rspamd` the rspamd pid file is in that directory correctly (I also tried changing the directory to `/var/run/rspamd` with same user and group permissions. In all cases the startup and log does not show any error except that it ignores my config and instead listens on default ports

**Comment by fkrauthan** [comment] 2018-02-11 23:53
This ticket is obsolete. I found the cause. My config permissions where to restrictive. Rspamd user had no read permission to access my config files. Problem was that the logfile did not indicate that it could not read the config file and instead just ignored them. After changing permission everything is working fine.

**Comment by moisseev** [comment] 2018-02-12 05:35
Why have you closed the issue?
> Problem was that the logfile did not indicate that it could not read the config file and instead just ignored them.

Although it is a different problem, but it still should be fixed.

**Comment by fkrauthan** [comment] 2018-02-12 08:34
I was going to open a new bug. But I can also just reopen this bug if preferred.

**Comment by vstakhov** [comment] 2018-02-12 10:35
Which config files? rspamd.conf itself or some of its includes?

**Comment by vstakhov** [comment] 2018-02-12 10:41
In fact, I cannot reproduce anything:

```
2018-02-12 10:40:38 #5882(main) cfg; rspamd_config_read: ucl parser error: cannot open file /home/cebka/rspamd.build/permissions.conf: Permission denied
```

If main config file has bad permissions I also have a similar error and Rspamd fails to start.

**Comment by fkrauthan** [comment] 2018-02-12 20:27
@vstakhov I see this issue with included config files in the `local.d` directory with wrong permission. The main config file is readable by _rspamd user

**Comment by vstakhov** [comment] 2018-02-12 20:30
Yes, and it is `try=true`. Perhaps, I should treat EPERM specially.

**Comment by fkrauthan** [comment] 2018-02-12 20:32
Yeah I think at least a warning would be good. Its debatable if it should be a fatal error (as you try to configure something but the system can not apply that config). It took me quiet some time to figure out that the reason why my config is not working is because rspamd was not reading my configs and instead started up fine with default configs^^

**Comment by vstakhov** [comment] 2018-02-12 20:50
Well, I've added a workaround for this issue with `EPERM`.

**Closed** 2018-02-27 17:15 UTC
